import random
import os
from colorama import init, Fore, Style
import time


def shipAnimation_miss():
    
    os.system('cls' if os.name == 'nt' else 'clear')
    print(Style.RESET_ALL+f"             # #  ( )     ")
    print(Style.RESET_ALL+f"          ___#_#___|__        ")
    print(Style.RESET_ALL+f"         |___|__|____/           __     ")                           
    print(Style.RESET_ALL+f"      _  |____________|         |  |==         ")                                                                           
    print(Style.RESET_ALL+f" _-==/___]_|__|____[___\________/__\_ .7")                   
    print(Style.RESET_ALL+f"|                                BB-61/")               
    print(Style.RESET_ALL+f"\____________________________________/")
    time.sleep(.5)
    os.system('cls' if os.name == 'nt' else 'clear')
    print(Style.RESET_ALL+f"             # #  ( )     ")
    print(Style.RESET_ALL+f"          ___#_#___|__        ")
    print(Style.RESET_ALL+f"         |___|__|____/           __     ")                           
    print(Style.RESET_ALL+f"      _  |____________|         |  |==    8--->>>>        ")                                                                           
    print(Style.RESET_ALL+f" _-==/___]_|__|____[___\________/__\_ .7")                   
    print(Style.RESET_ALL+f"|                                BB-61/")               
    print(Style.RESET_ALL+f"\____________________________________/")
    time.sleep(.5)
    os.system('cls' if os.name == 'nt' else 'clear')
    print(Style.RESET_ALL+f"             # #  ( )     ")
    print(Style.RESET_ALL+f"          ___#_#___|__        ")
    print(Style.RESET_ALL+f"         |___|__|____/           __     ")                           
    print(Style.RESET_ALL+f"      _  |____________|         |  |==                8--->>>>        ")                                                                           
    print(Style.RESET_ALL+f" _-==/___]_|__|____[___\________/__\_ .7")                   
    print(Style.RESET_ALL+f"|                                BB-61/")               
    print(Style.RESET_ALL+f"\____________________________________/")
    time.sleep(.5)
    os.system('cls' if os.name == 'nt' else 'clear')
    print("           _      ")   
    print(" _ __ ___ (_)___ ___ ")
    print("| '_ ` _ \| / __/ __|")
    print("| | | | | | \__ \__ \ ")
    print("|_| |_| |_|_|___/___/")
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')

def shipAnimation_hit():
    
    os.system('cls' if os.name == 'nt' else 'clear')
    print(Style.RESET_ALL+f"             # #  ( )     ")
    print(Style.RESET_ALL+f"          ___#_#___|__        ")
    print(Style.RESET_ALL+f"         |___|__|____/           __     ")                           
    print(Style.RESET_ALL+f"      _  |____________|         |  |==         ")                                                                           
    print(Style.RESET_ALL+f" _-==/___]_|__|____[___\________/__\_ .7")                   
    print(Style.RESET_ALL+f"|                                BB-61/")               
    print(Style.RESET_ALL+f"\____________________________________/")
    time.sleep(.5)
    os.system('cls' if os.name == 'nt' else 'clear')
    print(Style.RESET_ALL+f"             # #  ( )     ")
    print(Style.RESET_ALL+f"          ___#_#___|__        ")
    print(Style.RESET_ALL+f"         |___|__|____/           __     ")                           
    print(Style.RESET_ALL+f"      _  |____________|         |  |==    8--->>>>        ")                                                                           
    print(Style.RESET_ALL+f" _-==/___]_|__|____[___\________/__\_ .7")                   
    print(Style.RESET_ALL+f"|                                BB-61/")               
    print(Style.RESET_ALL+f"\____________________________________/")
    time.sleep(.5)
    os.system('cls' if os.name == 'nt' else 'clear')
    print(Style.RESET_ALL+f"             # #  ( )     ")
    print(Style.RESET_ALL+f"          ___#_#___|__        ")
    print(Style.RESET_ALL+f"         |___|__|____/           __     ")                           
    print(Style.RESET_ALL+f"      _  |____________|         |  |==                8--->>>>        ")                                                                           
    print(Style.RESET_ALL+f" _-==/___]_|__|____[___\________/__\_ .7")                   
    print(Style.RESET_ALL+f"|                                BB-61/")               
    print(Style.RESET_ALL+f"\____________________________________/")
    time.sleep(.5)
    os.system('cls' if os.name == 'nt' else 'clear')
    print(" _     _ _   ")   
    print("| |__ (_) |_ ")
    print("| '_ \| | __|")
    print("| | | | | |_  ")
    print("|_| |_|_|\__|")      
    time.sleep(1)
    os.system('cls' if os.name == 'nt' else 'clear')

